(function(root){
  const languages = [
    ["zh", "Chinese (Simplified)"],
    ["en", "English"],
    ["ru", "Russian"],
    ["es", "Spanish"],
    ["pt-BR", "Portuguese (Brazilian)"],
    ["ja", "Japanese"],
    ["de", "German"],
    ["ko", "Korean"],
    ["fr", "French"],
    ["tr", "Turkish"],
    ["pl", "Polish"],
    ["zh-TW", "Chinese (Traditional)"],
    ["it", "Italian"],
    ["th", "Thai"],
    ["vi", "Vietnamese"],
    ["id", "Indonesian"],
    ["uk", "Ukrainian"],
    ["ar", "Arabic"],
    ["cs", "Czech"],
    ["hu", "Hungarian"],
    ["nl", "Dutch"],
    ["fa", "Persian"],
    ["ro", "Romanian"],
    ["hi", "Hindi"],
    ["fil", "Filipino"],
    ["el", "Greek"],
    ["bg", "Bulgarian"],
    ["sr", "Serbian"],
    ["sw", "Swahili"],
    ["he", "Hebrew"]
  ];
  root.VNRevivalTranslatorLanguages = languages;
})(typeof globalThis !== "undefined" ? globalThis : this);
